name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: >
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

  prepare-release:
    name: Prepare GitHub Release
    needs:
    - build
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Mandatory for making GitHub Releases

    steps:
    - name: Check if GitHub Release exists
      id: release-check
      run: |
        if gh release view '${{ github.ref_name }}' --repo '${{ github.repository }}'; then
          echo "exists=true" >> $GITHUB_ENV
        else
          echo "exists=false" >> $GITHUB_ENV
        fi
    - name: Create GitHub Release if not exists
      if: ${{ env.exists == 'false' }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release create \
          '${{ github.ref_name }}' \
          --repo '${{ github.repository }}' \
          --notes "Release for tag ${{ github.ref_name }}"

  sign-distribution:
    name: Sign Python 🐍 distribution 📦 and upload to GitHub Release
    needs:
    - prepare-release
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Mandatory for making GitHub Releases
      id-token: write  # Mandatory for sigstore

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v3.0.0
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >
        gh release upload
        '${{ github.ref_name }}' dist/**
        --repo '${{ github.repository }}'
